export const DOM = {
  mainContainer: document.getElementById('main-container'),
  startScreen: document.getElementById('start-screen'),
  gameScreen: document.getElementById('game-screen'),
  endScreen: document.getElementById('end-screen'),
  startButton: document.getElementById('start-button'),
  restartButton: document.getElementById('restart-button'),
  scoreEl: document.getElementById('score'),
  cardCounterEl: document.getElementById('card-counter'),
  nextCardContainer: document.getElementById('next-card-container'),
  timeline: document.getElementById('timeline'),
  finalScoreEl: document.getElementById('final-score'),
  correctAnswersEl: document.getElementById('correct-answers'),
  wrongAnswersEl: document.getElementById('wrong-answers'),
  resumeModal: document.getElementById('resume-modal'),
  resumeYesButton: document.getElementById('resume-yes-button'),
  resumeNoButton: document.getElementById('resume-no-button'),
  resultsModal: document.getElementById('results-modal'),
  finalScoreModalEl: document.getElementById('final-score-modal'),
  correctAnswersModalEl: document.getElementById('correct-answers-modal'),
  wrongAnswersModalEl: document.getElementById('wrong-answers-modal'),
  closeResultsModalButton: document.getElementById('close-results-modal'),
  playAgainButton: document.getElementById('play-again-button'),
};
